### ISSUE TITLE
Makefile won't rebuild

### ISSUE THREAD

**Issue by tobiola** [mihaigalos/miniboot#1]
pi@raspberrypi:~/XX-Core/arduino/miniboot/src $ make rebuild

-------- start --------

Cleaning project:
rm -f miniboot.hex
rm -f miniboot.eep
rm -f miniboot.obj
rm -f miniboot.cof
rm -f miniboot.elf
rm -f miniboot.map
rm -f miniboot.obj
rm -f miniboot.a90
rm -f miniboot.sym
rm -f miniboot.lnk
rm -f miniboot.lss
rm -f miniboot.o I2C-master-lib/i2c_master.o  
rm -f  miniboot.lst I2C-master-lib/i2c_master.lst
rm -f miniboot.s I2C-master-lib/i2c_master.s
rm -f miniboot.d I2C-master-lib/i2c_master.d
rm -f .dep/* 
rm -f bootloader.h
Errors: none
-------- end --------

sh: 1: avr-g++: not found
Makefile:205: recipe for target 'gccversion' failed
make: *** [gccversion] Error 127

**Comment by mihaigalos** [comment]
It *might* have something to do with missing avr-g++, don't you think? If you are using raspian, you need to install a toolchain which enables you to cross-compile to avr.
