### ISSUE TITLE
Escape the double quotes

### ISSUE THREAD

**Issue by chaifeng** [mihaigalos/miniboot#14]
https://github.com/mihaigalos/miniboot/blob/c4ada3cf2a77084789ad1fbf86236aecb4a9d071/scripts/post_summary.sh#L9

    curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST \
        -d "{\"body\": \"${push_message}\"}" \
        "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"

**Comment by mihaigalos** [comment]
Fixed with [this](https://github.com/mihaigalos/miniboot/commit/579425b10bd467950763d2bf54acb3c118bdd0ff) commit.
