### ISSUE TITLE
I2C master library is not available anymore

### ISSUE THREAD

**Issue by diodenschein** [mihaigalos/miniboot#28]
https://github.com/g4lvanix/I2C-master-lib/

Seems to be gone. 
Is there a way to still build miniboot?

**Comment by mihaigalos** [comment]
> Seems to be gone.
> Is there a way to still build miniboot?

That’s nasty. I still have the repo cloned on my PC. I’ll upload the lib again once I get back from holiday.

**Comment by diodenschein** [comment]
That would be awsome, thank you.

**Comment by mihaigalos** [comment]
@diodenschein : please try it again, unfortunately GitHub closed this issue once all associated PRs were merged.

**Comment by diodenschein** [comment]
Thank you! 
Can compile now, great.
